- Sonarr/Sonarr.php
The Accept header is required for API requests in the next version of Sonarr (current preview version). The current version of Sonarr seems to work fine with the header so should be safe to add now instead of waiting for the preview release to go mainstream.
> Adding required headers to Sonarr requests

- AdGuardHome/AdGuardHome.php
AdguardHome team introduced some bracking changes to their API, as a result widget stoped displaying stats.
This small fix simply enables functionality once again in a way that would work with previous versions of AdguardHome.
See more deatial about API changes here: https://github.com/AdguardTeam/AdGuardHome/blob/master/openapi/CHANGELOG.md
> Add support for AdguardHome +v0.99.0

- qBittorrent/qBittorrent.php
Addresses linuxserver/Heimdall-Apps#146
As per release notes here (https://www.qbittorrent.org/news.php) v4.2.0 enforces modern API endpoints:
> WEBUI: Drop legacy WebAPI support (glassez)
I can't get the login piece to work though, works when testing with curl but not when running via PHP.  Workaround is to white-list the access to local IPs using the qBt preferences.
> Updated for qBitTorrent API v2

- Nzbget/Nzbget.php
This fixes an exception thrown when using login credentials containing special characters (such as " or /).
> urlencode NZBGet login details

- qBittorrent/qBittorrent.php
This fixes logins failing when using login credentials containing special special characters (such as a " or /).
> urlencode qBittorrent login details

- CouchPotato/CouchPotato.php
extra forward slash following normaliseurl()
> Bugfix: fix url() format

- Shinobi/app.json
Include https:// scheme, otherwise the URL was shown on the https://apps.heimdall.site/applications/foundation page as being a relative URL: https://apps.heimdall.site/applications/shinobi.video
> Update Shinobi's website URL

- Traefik/Traefik.php
- Traefik/config.blade.php
- Traefik/livestats.blade.php
Add configuration for the Traefik v2 API (#118).
This app in no longer compatible with Traefik v1 /health endpoint.
In order to support Traefik v2, we need to access its API, the `/health` endpoint is no more.
A whole new configuration has been introduced:
- **override_url**: API url in case it differs from the dashboard url, , leave blank otherwise
- **fields**: Change which data to display when pinned
- **ignore_tls**: Ignore TLS certificate validation result when querying the API
- **username**: Basic Authentication username in case API is protected, leave blank otherwise
- **password**: Basic Authentication password in case API is protected, leave blank otherwise
**Important:** While testing the configuration from the item configuration page, the TLS certificate is **ALWAYS** ignored, …
> Upgrade Traefik enhanced app to support Traefik v2

- Deluge/app.json
Used single quotes - causing invalid JSON evaluation. Changed to double quotes
> Fixing app.json

- Overseerr/Overseerr.php
Update `test()` function to use an API endpoint that requires auth, so the function also verifies the API key
> Fix Overseerr test() function

- ruTorrent/livestats.blade.php
- ruTorrent/ruTorrent.php
Hiding idle speeds on live stats at the request of the original author.
> ruTorrent: Hide idle speed

- Overseerr/Overseerr.php
- Overseerr/livestats.blade.php
**Do not merge until sct/overseerr#905 has been merged into `master`**
Updates the Overseerr enhanced app to display the number of "processing" requests (approved but not yet available) instead of the total number of approved requests (including available items).
> Update Overseerr enhanced app to reflect API changes

- Kodi/Kodi.php
- Kodi/app.json
- Kodi/config.blade.php
- Kodi/livestats.blade.php
- openmediavault/app.json
- openmediavault/config.blade.php
- openmediavault/livestats.blade.php
- openmediavault/openmediavault.php
Update Kodi to display library statistics.
This application is a little more resource-heavy:
Kodi's JSON-RPC does not have a sort of "GetStatistics/GetCounts" call, so we need to call individual library components to get the total numbers. This can become network-heavy if you have a gigantic library, I guess.
To-Do: option to replace the library stats with "Now playing" info, in case there's an active player.
> Enhanced Kodi app

- Emby/config.blade.php
- Jellyfin/config.blade.php
The line code copied from NextCloud config.blade.php, that fix the error querying null/empty additional stats. Works on emby and jellyfin.
{!! Form::select('config[availablestats][]', App\SupportedApps\APP_NAME\APP_NAME::getAvailableStats(), isset($item) ? ($item->getConfig()->availablestats ?? null) : null, array('multiple'=>'multiple')) !!}
> Fix the error after empty API creation.

- Plex/Plex.php
Fixes https://github.com/linuxserver/Heimdall-Apps/issues/292
This updates the Plex enhanced app to support custom port numbers and SSL, rather than hard coding port 32400.
> Allow scheme and port to be specified for Plex

- CouchPotato/CouchPotato.php
1. pass correct object property onto Illuminate\Support\Collection
2. fix negative (NOT) filtering
> Bugfix: CouchPotato livestats()

- Jellyfin/Jellyfin.php
leading forward-slash in URL caused a 404 response header
> Bugfix: Jellyfin livestats() url

- Radarr/Radarr.php
Tested on Radarr nightly (v4) and it works fine. You now get live stats and have a working API test button.
Fix #337
> Properly fix the Radarr v3 API usage

- Bazarr/Bazarr.php
- Bazarr/livestats.blade.php
- Radarr/Radarr.php
Not backward compatible as the API had a complete rework in 0.9.4. More than 92% of users are using 0.9.5 or greater anyway. Those who aren't should upgrade as much of the providers are probably broken in their old versions.
> Fixed Bazarr tile to work with recent versions of the API (v0.9.4 or greater)

- Sonarr/Sonarr.php
- Sonarr/app.json
currently the `/api/v3/wanted/missing` endpoint returns an error, as a recent change requires sortKey to be passed to this.
Updating the call with a sortKey so that the value can be returned again.
> Fix: Sonarr Enhanced missing items

- Radarr/app.json
Changed Radarr to light as default as the Radarr logo is dark
k
> Change Radarr to light as default

- Bookstack/Bookstack.php
This fixes a double slash problem in Bookstack enhanced app. With those / in place it generates the URL as // which results in a 404 not found.
> Fix double slashes in URL

- Bookstack/Bookstack.php
This change fixes multiple forward-slashes in URL by trimming the provided URL and endpoint path and adding one between them - this makes the behaviour more consistent.
Also adds the "page" endpoint to return the total number of pages.
> [Update] BookStack - Normalise "/" in url and add "pages"

- Transmission/Transmission.php
Display the correct number of seeding and leeching torrents based on status code. 
Based on the status code documentation here: https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md
> fix: display correct seeding and leeching torrent count

- Plex/Plex.php
- Plex/livestats.blade.php
Should fix #540
It seems [this commit](https://github.com/linuxserver/Heimdall-Apps/commit/8dc8d0dc206c570cde44bbbe1d1fecdb2a82f30f) accidentally removed the code to set the __recently_added__ variable. I added it back.
Also made the two template variables optional to avoid future errors.
> fix: Plex livestats

- Portainer/config.blade.php
- Transmission/config.blade.php
Right now both apps will easily lock out the user when they are polled too often.
> fix: increase poll intervals for Portainer, Transmission

- qBittorrent/qBittorrent.php
Closes #564 
Adjusts call to `parent::execute()` to pass null as the third argument, rather than false. This prevents a `TypeError` from being thrown when ever the application attempts to pull live stats or test the API connection.
> Update execute(...) call use correct argument types in Qbittorrent

- PaperlessNgx/PaperlessNgx.php
- PaperlessNgx/app.json
- PaperlessNgx/config.blade.php
- PaperlessNgx/livestats.blade.php
- PaperlessNgx/paperlessngx.svg
The original paperless was discontinued by the author long time ago and even the first single person driven fork (paperless-ng) is discontinued.
The latest active fork is paperless-ngx and community driven.
I also made this an enhanced app. The tile now shows the document count if an api key is provided.
> Use latest paperless fork and enhance the app

- PaperlessNgx/PaperlessNgx.php
@keriati sorry but somehow I pushed a version with a faulty auth header...
> fix(): PaperlessNgx auth header

- Tar1090/Tar1090.php
- Tar1090/livestats.blade.php
This will fix typo issues in tar1090 which causes the details not being shown.
> Fix typo in tar1090

- AVMFritzbox/AVMFritzbox.php
I just switched to Heimdall 2.5.4 and noticed the queue change. Because of this I now want to set $status from inactive from active because the app pulls live bandwith data of the internet connection.
> fix(AVMFritzbox): increase call intervall

- Nightscout/app.json
Apologies, just noticed I'd used the wrong license for Nightscout as per: https://github.com/nightscout/cgm-remote-monitor/blob/master/LICENSE
Correcting license to GNU Affero General Public License v3.0
> Updated Nightscout license

- Radarr/Radarr.php
Only display missing movies if they are available (therefore truely missing) and monitored.
In Radarr those show up as "Wanted" rather than missing (missing ignores the availability).
This is similar to #437 (without the merge conflicts).
> Radarr: Make missing stat more meaningful (2nd attempt)

- openmediavault/openmediavault.php
As reported in https://github.com/linuxserver/Heimdall/issues/1093, openmediavault broke API support with https://github.com/openmediavault/openmediavault/commit/03a5d57406486dc3a12cfdee0e34b230e6cc1af9 
This PR adapts API call to latest OMV RPC API response.
> Update openmediavault rpc parameter

- Syncthing/livestats.blade.php
Enhancement to the readability of the remaining file size in the WebUI.
> Syncthing: Show remaining GB instead of bytes

- AVMFritzbox/AVMFritzbox.php
Restores API access when DNS is not handled by the Fritzbox and no DNS rewrite for 'http://fritz.box' is configured.
> Replace hardcoded base URL with config URL

- Proxmox/livestats.blade.php
It groups the numbers together so it looks like '1/1' instead of '1 /1'.
> moved the span tags to look better for the proxmox livestats blade.

- openmediavault/openmediavault.php
As reported in [linuxserver/Heimdall#651](https://github.com/linuxserver/Heimdall-Apps/issues/651), openmediavault moved the CPU stats RPC to a new one: `System::getCpuStats`
> Update openmediavault rpc properties for CPU Stats

- AVMFritzbox/config.blade.php
This PR simply adds the default override url config option for the AVM Fritzbox app.
This is needed if the user is running a reverse proxy like NGINX and would like to enter the proxied URL like https://fritzbox.example.com as linking url.
As the URL is used with a custom port for the API queries, these fail when doing so.
To fix this, I enabled the override option for the url.
Now I am able to specify the linking url as https://fritzbox.example.com and the API (override) url as http://10.0.0.1 (or any other IP/domain)
> AVMFritzBox: add override url config to allow reverse proxied linking urls

- Fronius/Fronius.php
A small improvement to remove all decimals from the Fronius solar inverter output, specifically important for the recent GEN24 model which outputs 14 decimals by default!
> adding rounding to power/day valyes in fronius.php

- .github/workflows/linter.yml
- .github/workflows/main.yml
- .github/workflows/prchecks.yml
- .github/workflows/svgo.yml
Bump versions of actions and switch to super-lint/super-linter/slim which is much more up-to-date than the github/super-linter fork.
> Update workflows and super-linter

- Jellyseerr/Jellyseerr.php
- Jellyseerr/config.blade.php
Jellyseerr app is setup with counts of **pending** requests and **open** issues by default. My Jellyseerr is setup to auto approve all requests. So my pending requests count will always be 0 with these defaults. Added config options to change default settings for requests and issues counts shown for the Jellyseerr app.
> Jellyseerr count options

- TrueNASCORE/TrueNASCORE.php
- TrueNASCORE/livestats.blade.php
Previously, only total amounts of alerts was shown in the livestats. Commits add seperate mention of more critical alerts with a red background.
> Update TrueNASCORE livestats to differentiate between notices/info and alerts that need immediate attention

- Scrutiny/Scrutiny.php
- Scrutiny/app.json
- Scrutiny/config.blade.php
- Scrutiny/livestats.blade.php
enhances the scrutiny app to include the passed & failed drives
I really think that this should be a bit more.. LOUD when there's failed drives but, eh..
If there's more interesting information this should have instead it can be easily pulled.
Note: I tried to add this as a requested app first but it seems the apps list on the site caps out around the "R"s so I can't actually select scrutiny to request enhanced.
> feat: enhance scrutiny foundation app

- Jellyfin/Jellyfin.php
fixes #669
switches the authentication mechanism to be the non-deprecated `Authorization` header
https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f
as part of this, switches the jellyfin connectivity test to use `info` rather than `info/public` because `info/public` ignores all auth
this works against a live jellyfin server using the official jellyfin docker image
> fix: switch jellyfin to use non-deprecated auth mechanism

- Immich/Immich.php
The API test for Immich always fails as unauthorized because there is no 'x-api-key' header in the test request.
This patch works with Immich v1.107.2
> Add api headers to test

- PhotoPrism/PhotoPrism.php
- PhotoPrism/config.blade.php
Based on the code from @iwinstar, and following app password availability from photoprism the solution is working fine. 
Issue is described in https://github.com/linuxserver/Heimdall-Apps/issues/496
> Update code to support API authentication from Photoprism

- Bazarr/Bazarr.php
- Lidarr/Lidarr.php
- Prowlarr/Prowlarr.php
- Radarr/Radarr.php
- Readarr/Readarr.php
- Sonarr/Sonarr.php
Seems like at some point `normaliseurl` changed or someone edited the `/` off the next line causing all attempts to verify enhanced apps were set up correctly to fail. This should solve that by using the second input of the `normaliseurl` function.
> Fix *arr url creation

- Immich/Immich.php
The api URL is now `server/statistics`, and no more `server-info/statistics`
https://immich.app/docs/api/get-server-statistics
> Immich: Fixed incorrect api reference

- UniFi/UniFi.php
- UniFi/config.blade.php
This PR adds a "Self Hosted" switch to the config blade and uses the correct API URLs based on this switch. When the switch is enabled it uses the legacy URLs for Self Hosted controllers, when disabled (default) it uses the API URLs for the UDM hosted controller.
> Add support for Self Hosted UniFi Controllers

- Diaspora/Diaspora.php
- Diaspora/app.json
This integration no longer requires the external api and instead uses the local nodeInfo found at `https://diasporaURL/nodeinfo/2.1`. This pull requests also removes no longer relevant functions and available stats.
> Diaspora Enhanced App - Remove external api dependency

- Duplicati/Duplicati.php
Hi,
this PR solves #806 by adapting Duplicati.php for the new auth endpoint. Mostly done by ChatGPT as I'm no Web/PHP guy.
Tested on my server running Heimdall and Duplicati.
> fix: Adapt Duplicati.php to new auth endpoint using JWT

- Pihole/Pihole.php
- Pihole/config.blade.php
When using the wrong password for the API, the app fails to parse the response and just fails with the generic error message "Server error". This made it very hard for me to pinpoint the problem, because if the URL is invalid for example you will get an identical response.
So I improved the error handling when communicating with the API, and now it communicates the correct error message back to the user, for example "invalid password".
> Improve error handling in Pihole app

- UptimeKuma/UptimeKuma.php
The Uptime Kuma enhanced application displays its monitors Up/Down live counts.
However, an UptimeKuma/UptimeKuma.php typo in its livestats() function is failing.
Thus its Up and Down counts are always zero.
This PR fixes this issue by using the correct operator: change an !== operator to the === operator.
> fix: UptimeKuma Up/Down counts are always zero

- Immich/Immich.php
Because an app plate is quite small, displaying large numbers can be problematic as they collide and cannot be distinguished.
This commit fixes this issue by displaying large numbers using fewer characters and ISO suffixes, up to G (giga, 10^9).
Here is an example of the problematic behaviour:
<pre>
+-----------------------+
| PHOTOS  VIDEOS  USAGE |
|   14698443 0.94GiB    |
+-----------------------+
</pre>
The 14,698 photo count collides with the 443 video count.
This commit changes the display to:
<pre>
+-----------------------+
| PHOTOS  VIDEOS  USAGE |
|   15k    443  0.94GiB |
+-----------------------+
</pre>
> Immich: display large numbers with suffixes

- Immich/livestats.blade.php
Immich blades displays three metrics: one for the number of photos, one for the number of videos and one for the total space usage of its server.
This commit fixes an issue where the titles of those metrics are colliding into a single word: "PHOTOSVIDEOSUSAGE", which impair readability.
Before this commit, the blade reads:
<pre>
+-------------------+
| PHOTOSVIDEOSUSAGE |
|   265 443 0.94GiB |
+-------------------+
</pre>
After this commit, the blade reads:
<pre>
+-------------------+
| PICS  VIDS  USAGE |
|  265  443 0.94GiB |
+-------------------+
</pre>
> Immich: Fix blade's coliding titles

- Memos/Memos.php
- Memos/app.json
- Memos/config.blade.php
- Memos/livestats.blade.php
Implement livestats functionality to display memo count and add config support for API access. Enable enhanced app features in app.json.
> feat(Memos): add livestats and config support for Memos app

- Audiobookshelf/Audiobookshelf.php
- Audiobookshelf/livestats.blade.php
- Rename "Total Playtime" to "Playtime" for brevity
- Add book count to stats display
- Simplify time format by removing seconds
- Clean up constructor and unused code
- Update API endpoint for testing
> feat(Audiobookshelf): enhance stats display and add book count
