linuxserver/Heimdall-Apps

- qBittorrent/config.blade.php
- qBittorrent/qBittorrent.php
This works both with and without authentication required.
> Update qBittorrent enhanced app to support login

- Cabot/Cabot.php
- Cabot/app.json
- Cabot/config.blade.php
- Cabot/livestats.blade.php
Found a way to add extended functionality...
> Add Cabot Extended

- Miniflux/Miniflux.php
- Miniflux/app.json
- Miniflux/config.blade.php
- Miniflux/livestats.blade.php
Displays the number of unread feed entries.
> Add Miniflux extended

- Netdata/Netdata.php
- Netdata/app.json
- Netdata/config.blade.php
- Netdata/livestats.blade.php
Displays the number of warning and critical alerts.
> Add Netdata extended

- Lidarr/Lidarr.php
- Lidarr/app.json
- Lidarr/config.blade.php
- Lidarr/livestats.blade.php
live stats displaying Missing & Queue values on tile
> Updated Lidarr to be an enhanced app

- Mylar/Mylar.php
- Mylar/app.json
- Mylar/config.blade.php
- Mylar/livestats.blade.php
Live stats displaying Missing(wanted) and upcoming issues on the tile.
> Make Mylar an enhanced app

- Jupyter/Jupyter.php
- Jupyter/app.json
- Jupyter/jupyter.svg
This fulfills https://github.com/linuxserver/Heimdall/issues/338 and adds in Jupyter Notebooks as a Foundation App. Jupyter is an interactive programming tool.
> Add Jupyter

- Octoprint/Octoprint.php
Fixes [this](https://github.com/linuxserver/Heimdall/issues/351) issue
> Fix Octoprint Progress scaling

- Pihole/Pihole.php
- Pihole/livestats.blade.php
Report blocked today and percent blocked
> PiHole: Display more useful stats

- Sympa/Sympa.php
- Sympa/app.json
- Sympa/sympa.svg
Website: https://www.sympa.org/
Logo: https://www.sympa.org/logos/logos
License Information: https://github.com/sympa-community/sympa/blob/master/COPYING
> Add Sympa App

- TYPO/TYPO.php
- TYPO/app.json
- TYPO/typo3.svg
Add TYPO3 CMS
Website: https://typo3.org/
Spelling Guide: https://typo3.org/project/brand/spelling-typo3/
License Information: https://typo3.org/project/licenses/
Logo taken from their official assets: https://typo3.org/project/brand/style-guide/
> Add TYPO3 App

- ruTorrent/app.json
- ruTorrent/config.blade.php
- ruTorrent/livestats.blade.php
- ruTorrent/ruTorrent.php
It seems to be requested by a lot of users.
Here we go! 
<3
> Add ruTorrent enhanced app

- ruTorrent/config.blade.php
- ruTorrent/livestats.blade.php
- ruTorrent/ruTorrent.php
Add optional basic auth for RPC2 connection
Add exception handling.
Change ul/dl display to be more inline with other applications.
Fixing some typos.
> ruTorrent Auth & tag display change

- Ombi/Ombi.php
- Ombi/app.json
- Ombi/config.blade.php
- Ombi/livestats.blade.php
Adds enhanced app capablities to Ombi.  Will display the number of pending requests and the number of approved but unavailable requests.
> Enhanced Application for Ombi

- Grocy/app.json
The file extension is for an SVG but the file is a PNG
> Fix Grocy Icon Extension

- AdGuardHome/config.blade.php
- Deluge/config.blade.php
- Miniflux/config.blade.php
- Nzbget/config.blade.php
- Transmission/config.blade.php
- qBittorrent/config.blade.php
- ruTorrent/config.blade.php
This fixes the "Illegal string offset 'name'" bug, https://github.com/linuxserver/Heimdall/issues/433
I have only tested Deluge, but they seem to share the same issue.
> Fixed Illegal string offset bug

- Adminer/app.json
Changed "conist" to "consists"
> Fixed Typo

- Jellyfin/Jellyfin.php
- Jellyfin/app.json
- Jellyfin/config.blade.php
- Jellyfin/livestats.blade.php
Make enhanced and allow the user to select wich stats to show.
> Make Jellyfin enhanced

- GitLab/GitLab.php
- GitLab/app.json
- GitLab/config.blade.php
- GitLab/livestats.blade.php
Gitlab enhanced app shows health status of gitlab instance with health token and also count project and active users of the instance with a private access token. Unfortunately this only works if you are an admin user of the instance.
> Gitlab enhanced

- FreshRSS/FreshRSS.php
- FreshRSS/config.blade.php
- FreshRSS/livestats.blade.php
Display the number of unread items.
> FreshRSS is now enhanced

- Emby/Emby.php
- Emby/app.json
- Emby/config.blade.php
- Emby/livestats.blade.php
Make Emby enhanced based on pull request #192
> Make Emby enhanced

- Syncthing/Syncthing.php
- Syncthing/app.json
- Syncthing/config.blade.php
- Syncthing/livestats.blade.php
* add a configuration for `apikey` that is optional so that existing apps can
convert to it
* add needed files and needed bytes to the blade
> Convert Syncthing into an enhanced app

- Freenas/Freenas.php
- Freenas/app.json
- Freenas/config.blade.php
- Freenas/livestats.blade.php
Add optional configuration options and related files to turn FreeNAS into enhanced app.
> Convert FreeNAS into enhanced app

- FreshRSS/app.json
- FreshRSS/config.blade.php
This fixes the issue described in #254 and enables the enhanced functionality.
> Fix for FreshRSS

- Bazarr/Bazarr.php
- Bazarr/app.json
- Bazarr/config.blade.php
- Bazarr/livestats.blade.php
Added stats for Bazarr, for missing subtitles (Movies and Series).
I tried clicking the "Request enhanced app" button on the web page, not sure if anything happened.
I've tested this locally, screenshot attached
> Bazarr enhanced app

- Bookstack/Bookstack.php
- Bookstack/app.json
- Bookstack/config.blade.php
- Bookstack/livestats.blade.php
Enhanced Bookstack
Shows the number of shelves, books and chapters (selectable in config)
> Enhanced Bookstack

- Nextcloud/Nextcloud.php
- Nextcloud/app.json
- Nextcloud/config.blade.php
- Nextcloud/livestats.blade.php
Enhanced Nextcloud
Shows the relative usage, used space, free space and total space for the given user (selectable in config)
> Enhanced Nextcloud

- PRTG/PRTG.php
- PRTG/config.blade.php
- PRTG/livestats.blade.php
- Fix the config settings in extended section to persist so they are not empty when editing application tile.
- Use base64 encoded images instead of from the `/help` url. Those didn't load for me and returned a 404.
> PRTG Fixes

- Plex/Plex.php
- Plex/app.json
- Plex/config.blade.php
- Plex/livestats.blade.php
- Added Recently Added value to tile
- Added On Deck value to tile
- Added config for Plex Token
- Added override for api url
- Changed the enhanced value in `app.json` to `true`
> Plex Enhanced

- Navidrome/Navidrome.php
- Navidrome/app.json
- Navidrome/config.blade.php
- Navidrome/livestats.blade.php
Enhanced Navidrome using the [compatible](https://www.navidrome.org/docs/developers/subsonic-api/#supported-subsonic-api-endpoints) Subsonic API endpoints [`ping`](http://www.subsonic.org/pages/api.jsp#ping) and [`getNowPlaying`](http://www.subsonic.org/pages/api.jsp#getNowPlaying).
Screenshot:
> Enhanced Navidrome

- Portainer/Portainer.php
- Portainer/app.json
- Portainer/config.blade.php
- Portainer/livestats.blade.php
Displaying the amount of running and stopped containers.
Here's what it looks like:
> Enhanced Portainer app

- FoldingHome/FoldingHome.php
1) apparently the way you get sid changed, now you have to query an endpoint to get it (this is what `js/main.js` script does), so I've updated it
2) there can be cases where the status isn't READY, in these cases there's no percentdone and eta fields, so here's a fallback for these
3) removed sanitizeJSON function, apparently it's never used and it works without it
> Fixed FoldingAtHome

- Ghost/Ghost.php
- Ghost/app.json
- Ghost/config.blade.php
- Ghost/livestats.blade.php
Displaying amount of articles (draft + published). Couldn't fit scheduled there unfortunately.
Here's how it'll look like:
> Enhanced Ghost app

- Deluge/Deluge.php
Fixes #308
With one torrent downloading, and 5 seeding (1 actively seeding):
Sadly there's no stats for "actively seeding", and the "active" stat is the sum of actively leeching + actively seeding, so this'll have to do.
If you don't like relying on Laravel helper functions let me know, would be simple enough to rewrite with native php ones, just a bit less readable.
> Reworking Deluge livestats

- Bazarr/app.json
Added bazarr app for use in Heimdalljs
Queries both the series and movies endpoints over the API.
> add bazarr for heimdalljs

- Monica/Monica.php
- Monica/app.json
- Monica/config.blade.php
- Monica/livestats.blade.php
Updates Monica app to display total contact count.
> Monica enhanced app

- Bazarr/config.blade.php
This fixes the issue reported in #325
> Fixes #325 override_url config issue

- Octoprint/Octoprint.php
- Octoprint/livestats.blade.php
This fixes issue #357 and displays the following if octoprint is offline:
> Fix #357 octoprint internal server error

- Sonarr/Sonarr.php
Tested with Sonarr v4 and also working fine.
> Dropped legacy API endpoint and added support for v3 API

- Portainer/Portainer.php
Use a simple foreach loop instead of [0]
> Handle multiple Portainer Endpoints

- Wordpress/app.json
Wordpress to WordPress. 
ref: https://developer.wordpress.org/reference/functions/capital_p_dangit/
> Updated WordPress with capital P.

- .github/workflows/svgo.config.js
- .github/workflows/svgo.yaml
This action will automatically minify and remove dimensions from SVG files.
The only feature missing is the ability to crop icons to remove blank space arround the icon
> feat: add SVG optimiser action

- Proxmox/Proxmox.php
- Proxmox/app.json
- Proxmox/config.blade.php
- Proxmox/livestats.blade.php
* Uses API Tokens for better access control and session management
* Supports clusters of nodes
* if no nodes specified, all clustered nodes are used
* if listed as CSV, specific nodes are used
* VM and LXC counts are total, memory and CPU percentages are of the entire cluster's resources
> Update Proxmox to enhanced app

- Readarr/Readarr.php
- Readarr/app.json
- Readarr/config.blade.php
- Readarr/livestats.blade.php
Enhanced app for readarr.
Shows missing books, and books upcoming in a month
.
> Readarr Enhanced App, missing books, and 1 month upcoming books.

- Traefik/config.blade.php
make it a password field rather than a plain text field so the password is hidden
> Make Traefik password field protected

- openmediavault/openmediavault.php
Added an indicator to show package update status.
The indicator will show "X" if packages need to be updated; functions a sort of alert-type indicator.
> OMV: add pkgs update status

- Mylar/Mylar.php
https://github.com/mylar3/mylar3/wiki/getWanted
> Update Mylar.php because of API changes.

- Portainer/config.blade.php
Similar to #172  , fixing issue https://github.com/linuxserver/Heimdall/issues/433
Fixed Illegal string offset bug for Portainer App.
> Fixed Illegal string offset bug for Portainer

- qBittorrent/qBittorrent.php
Version api test should use cookies from login.
> fix qBittorrent test

- HomeAssistant/HomeAssistant.php
- Homebridge/Homebridge.php
- NginxProxyManager/NginxProxyManager.php
- Spotweb/Spotweb.php
- WaniKani/WaniKani.php
- openmediavault/openmediavault.php
- qBittorrent/qBittorrent.php
> fix: Update SupportedApps interface to use null instead of false

- Duplicati/Duplicati.php
- Duplicati/app.json
- Duplicati/config.blade.php
- Duplicati/livestats.blade.php
> Upgrade Duplicati to enhanced app

- AVMFritzbox/AVMFritzbox.php
- AVMFritzbox/app.json
- AVMFritzbox/config.blade.php
- AVMFritzbox/livestats.blade.php
Currently only works with a Fritzbox inside the same local network as the heimdall installation.
> feat(): upgrade AVMFritzbox to enhanced app

- Stash/Stash.php
- Stash/config.blade.php
- Stash/livestats.blade.php
I added a statistic check for the number and size of scenes. Added API key to the settings.
> Stash: Add API

- Portainer/Portainer.php
- Portainer/config.blade.php
> feat: Add disable tls verification option to Portainer

- GitLab/GitLab.php
- GitLab/config.blade.php
- related to https://github.com/linuxserver/Heimdall/issues/1108
> fix: add missing data-config fields to gitlab app

- Syncthing/Syncthing.php
Before livestats always displayed 0 for needed bytes and needed files. This should fix the problem.
> Fix Syncthing's livestats

- UniFi/UniFi.php
- UniFi/app.json
- UniFi/config.blade.php
- UniFi/livestats.blade.php
Converting the Unifi app to enhanced app.
Displays:
- number of wlan clients
- number of lan clients
- wan availability %
> feat: add unifi os enhanced app

- UniFi/UniFi.php
Just a simple fix to handle the change in unifi api returning a lot of decimals on the uptime.
> Add number formatting

- UptimeRobot/UptimeRobot.php
- UptimeRobot/app.json
- UptimeRobot/uptimerobot.svg
> Add UptimeRobot app

- Mainsail/Mainsail.php
- Mainsail/app.json
- Mainsail/config.blade.php
- Mainsail/livestats.blade.php
Uses the unauthenticated Moonraker API to display the following:
- Printer state if not printing
- Print job duration and percent completed if printing
> Enhance Mainsail app

- MailCatcher/MailCatcher.php
- Mainsail/Mainsail.php
there were style issues getting caught by `phpcs` which somehow didn't get caught as part of previous reviews in the `MainSail` and `MailCatcher` applications
> chore: fix style issues in MainSail and MailCatcher apps

- Radicale/Radicale.php
- Radicale/app.json
- Radicale/radicale.svg
> Add Radicale foundation app

- .editorconfig
- .gitignore
- Proxmox/Proxmox.php
Hi, 
this fixes that no information shown for proxmox if one node of the cluster is turned of for some reason. 
Feel free to check and merge.
> Fix proxmox with offline node

- ruTorrent/ruTorrent.php
added
private $attrs;
private $vars;
changed:
$this->url("RPC2"),
to:
$this->url("plugins/rpc/rpc.php"),
tested with client in docker and ubuntu-image
> fixed ruTorrent

- Gogs/Gogs.php
- Gogs/app.json
- Gogs/config.blade.php
- Gogs/livestats.blade.php
Show number of repos and organizations
> Make Gogs Enhanced App

- Guacamole/Guacamole.php
- Guacamole/app.json
- Guacamole/config.blade.php
- Guacamole/livestats.blade.php
Show number of connections and number of active connection.
> Make Guacamole Enhanced app

- FileBrowser/FileBrowser.php
- FileBrowser/app.json
- FileBrowser/config.blade.php
- FileBrowser/livestats.blade.php
> Make FileBrowser Enhanced App

- Gitea/Gitea.php
- Gitea/app.json
- Gitea/config.blade.php
- Gitea/livestats.blade.php
Show, repos, orgs and users. Chose by the user
> Make Gitea Enhanced App

- Gotify/Gotify.php
- Gotify/app.json
- Gotify/config.blade.php
- Gotify/livestats.blade.php
Now the app shows number of apps/clients and messages in the dashboard, tested myself and it works for me but maybe needs more testing if needed.
> Enhanced gotify

- Monit/Monit.php
- Monit/config.blade.php
- Monit/livestats.blade.php
- Fixed auth of monit
- Add some value from Monit "system"  for livestats
- A dropdown menu to selecte the tiltle of value
- some other fix
> Fix for monit

- Netdata/Netdata.php
- Netdata/config.blade.php
- Netdata/livestats.blade.php
get the value of System like Load/Cpu/Memory/Disk/Netwoks staus for livestats
make a dropdown menu of these value
> Enhance-For-Netdata

- Transmission/Transmission.php
Make Transmission app work for Transmission 4.0
> Fix-for-Transmission4

- Pihole/Pihole.php
- Pihole/config.blade.php
- Pihole/livestats.blade.php
Added support for v5 and v6, i think the code can be improved as the pihole dev team rewrote all the api to work with SID and CSRF, also added domains count.
> Enhanced pi hole

- Pihole/Pihole.php
- Pihole/config.blade.php
> add support to skip tls verification

- ArchiSteamFarm/ArchiSteamFarm.php
> Added urlencode so it accepts special characters

- Scrutiny/config.blade.php
Fixed [[BUG] - Scrutiny not showing any configuration options #807](https://github.com/linuxserver/Heimdall-Apps/issues/807#issue-2785459199)
> Update Scrutiny config.blade.php so it loads during config

- Plex/Plex.php
- Plex/config.blade.php
- Plex/livestats.blade.php
The Plex status can be displayed in 2 media sections to show how much is there.
> Plex section status
